4 - Облачные технологии (Евдокимов)/LW1/LW1/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using LW1.Models;
using LW1.Providers;
using LW1.Data;
using LW1.Data.Repositories;

namespace LW1.Controllers
{
    public class HomeController : Controller
    {
        private readonly IUserProvider userProvider;
        private readonly IDomainRepositoryFactory repositoryFactory;

        public HomeController(IUserProvider userProvider, IDomainRepositoryFactory repositoryFactory)
        {
            this.userProvider = userProvider;
            this.repositoryFactory = repositoryFactory;
        }

        public IActionResult Index()
        {
            var projects = repositoryFactory.GetProjectRepository().GetProjectsByUserId(userProvider.CurrentUserId).ToList();
            return View(projects);
        }

        public IActionResult About()
        {
            ViewData["Message"] = "Your application description page.";

            return View();
        }

        public IActionResult Contact()
        {
            ViewData["Message"] = "Your contact page.";

            return View();
        }

        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

4 - Облачные технологии (Евдокимов)/LW1/LW1/Controllers/ProjectController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using LW1.CreateModels;
using LW1.Data.Repositories;
using LW1.Models.Project;
using LW1.Providers;
using Microsoft.AspNetCore.Mvc;

namespace LW1.Controllers
{
    public class ProjectController : Controller
    {
        private readonly IDomainRepositoryFactory repositoryFactory;
        private readonly IUserProvider userProvider;

        public ProjectController(IDomainRepositoryFactory repositoryFactory, IUserProvider userProvider)
        {
            this.repositoryFactory = repositoryFactory;
            this.userProvider = userProvider;
        }

        public IActionResult CreateProject()
        {
            return View();
        }

        public RedirectResult NewProject(ProjectCreateModel project)
        {
            var projectRepos = repositoryFactory.GetProjectRepository();
            var newProject = Project.CreateProject(userProvider.CurrentUserId, project.Name, project.MainUrl, project.KeyWords);
            projectRepos.Create(newProject);

            return Redirect("/Home/Index");
        }

        public IActionResult ViewProject(Guid id)
        {
            var repos = repositoryFactory.GetProjectRepository();
            var project = repos.GetProjectViewModelById(id);
            return View(project);
        }
    }
}

4 - Облачные технологии (Евдокимов)/LW1/LW1/Views/Home/About.cshtml
@{
    ViewData["Title"] = "About";
}
<h2>@ViewData["Title"]</h2>
<h3>@ViewData["Message"]</h3>

4 - Облачные технологии (Евдокимов)/LW1/LW1/Views/Home/Contact.cshtml
@{
    ViewData["Title"] = "Contact";
}
<h2>@ViewData["Title"]</h2>
<h3>@ViewData["Message"]</h3>

<address>
    Сидорчук А.О.
</address>

4 - Облачные технологии (Евдокимов)/LW1/LW1/Views/Home/Index.cshtml
@using Microsoft.AspNetCore.Identity
@model List<LW1.ViewModels.ProjectViewModel>

@inject SignInManager<ApplicationUser> SignInManager
@inject UserManager<ApplicationUser> UserManager

@{
    ViewData["Title"] = "";
}


@if (SignInManager.IsSignedIn(User))
{
    @if (Model.Any())
    {
        <div class="row"><h3>Ваши проекты</h3></div>
        <div class="row">
            <table class="table table-hover">
                <thead>
                    <tr>
                        <th>#</th>
                        <th>Название проекта</th>
                        <th>Количество ключевых слов</th>
                        <th>Последний срез</th>
                        <th></th>
                    </tr>
                </thead>
                <tbody>
                    @for (int i = 0; i < Model.Count; i++)
                    {
                        var elem = Model.ElementAt(i);
                        <tr>
                            <td>@(i + 1)</td>
                            <td>@elem.Name</td>
                            <td>@elem.KeyWords.Count</td>
                            @if (elem.LastSelection.HasValue)
                            {
                                <td>@elem.LastSelection.Value.ToLongDateString()</td>
                            }
                            else
                            {
                                <td>Срез не выполнен</td>
                            }
                            <td style="text-align:right"><a asp-route-id="@elem.Id" asp-controller="Project" asp-action="ViewProject" style="padding-right:5px"><i class="fas fa-search"></i></a></td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
    }
    else
    {
        <div class="row" style="text-align:center">
            <h3>У вас пока нет проектов!</h3>
            <a asp-controller="Project" asp-action="CreateProject">Создать проект</a>
        </div>
    }
}
else
{
    <div class="row" style="text-align:center">
        <h3>Войдите в систему, что бы увидеть свои проекты.</h3>
    </div>
}